[package]
name = "fetcher"
version = "0.1.0"
edition = "2024"

[dependencies]
jzon = "0.12.5"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
solana-transaction-error = { version = "2.2.1", features = ["serde"] }
solana-transaction-status-client-types = "2.2.7"
